defaults:
  - _self_
  - paths: default
  - model: ae
  - data: ae_data_module
  - loggers: [tensorboard, mlflow]
  - trainer: gpu
  - general: general
  - experiment: null

torch_matmul_precision: 'medium'

ckpt_path: null
