_target_: src.models.gan.GAN


lr: 0.0002
latent_dim: 1000

# optimizer:
#   _target_: torch.optim.Adam
#   _partial_: true
#   lr: 0.001

# scheduler:
#   _target_: transformers.get_linear_schedule_with_warmup
#   _partial_: true
#   # Сколько шагов warm‑up
#   num_warmup_steps: 3
#   # Общее число шагов обучения
#   num_training_steps: 100
